"""
retrain_bnf_surrogate.py — Retrain BNF RF surrogate on real published labels.

CONTEXT:
  The original bnf_surrogate_classifier.joblib was trained on synthetic bootstrap
  labels generated by the pipeline itself (circular). External validation gives
  Spearman r=0.35 against published site-level rates.

  This script retrains the surrogate using published BNF rates from
  apps/bnf/reference/bnf_measurements.csv as supervised training labels.
  Expected improvement: Spearman r from 0.35 → 0.50–0.65.

  WHY IT SHOULD WORK:
    Smercina et al. 2019 (Table S3) report that phylum-level composition +
    env covariates (pH, MAT, MAP) explain ~40–55% of variance in free-living
    BNF rates across NEON sites (r≈0.63–0.74 in their random forest models).
    Our baseline r=0.35 is below this because our training labels were circular.
    With real labels we should approach the literature-reported signal limit.

SCIENTIFIC CAVEAT:
  Site-level published rates (Smercina, Vitousek, Reed) are literature averages,
  not direct measurements of these specific samples. The training signal is
  real but the labels have uncertainty. This is acknowledged in the model card.

  The model is valid for RANK-ORDER screening (which sites/communities are more
  likely to support BNF) but NOT for absolute flux quantification.

Usage:
  python apps/bnf/scripts/retrain_bnf_surrogate.py \\
    --db /data/pipeline/db/soil_microbiome.db \\
    --bnf-csv apps/bnf/reference/bnf_measurements.csv \\
    --out-dir apps/bnf/models/

Output:
  apps/bnf/models/bnf_surrogate_classifier_v2.joblib
  apps/bnf/models/bnf_surrogate_regressor_v2.joblib
  apps/bnf/models/retrain_report.json
"""

from __future__ import annotations
import argparse
import csv
import json
import logging
import sqlite3
from pathlib import Path

import numpy as np

logger = logging.getLogger(__name__)

# Metadata feature names (must match validate_pipeline._build_feature_vector order)
_META_FEATURES = ["soil_ph", "organic_matter_pct", "clay_pct", "temperature_c", "precipitation_mm"]
_META_DEFAULTS = {"soil_ph": 6.5, "organic_matter_pct": 2.5, "clay_pct": 20.0,
                  "temperature_c": 15.0, "precipitation_mm": 600.0}


def _load_bnf_labels(csv_path: Path) -> dict[str, float]:
    """Load sample_id → normalised BNF rate (0–1) from bnf_measurements.csv."""
    labels: dict[str, float] = {}
    with open(csv_path) as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            sid = row.get("sample_id", "").strip()
            mf = row.get("measured_function", "")
            try:
                labels[sid] = float(mf)
            except (ValueError, KeyError):
                pass
    logger.info("Loaded %d BNF labels from %s", len(labels), csv_path)
    return labels


def _build_feature_matrix(
    db_path: str,
    labels: dict[str, float],
    min_samples: int = 50,
) -> tuple[np.ndarray, np.ndarray, list[str]]:
    """
    Query phylum profiles + env metadata for labelled samples.
    Returns (X, y, feature_names).

    Samples with no phylum_profile or missing env metadata get default values.
    Only samples present in `labels` are included.
    """
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    # Fetch all labelled samples
    rows = conn.execute(
        "SELECT c.sample_id, c.phylum_profile, "
        "s.soil_ph, s.organic_matter_pct, s.clay_pct, s.temperature_c, s.precipitation_mm "
        "FROM communities c "
        "JOIN samples s ON c.sample_id = s.sample_id "
    ).fetchall()
    conn.close()

    # Filter to labelled samples only
    rows = [r for r in rows if r["sample_id"] in labels]
    if len(rows) < min_samples:
        raise ValueError(
            f"Only {len(rows)} labelled samples found in DB (need ≥{min_samples}). "
            f"Run scripts/ingest/fetch_published_bnf.py first."
        )
    logger.info("Found %d labelled samples in DB", len(rows))

    # Discover all phylum feature names from non-null profiles
    all_phyla: set[str] = set()
    for r in rows:
        if r["phylum_profile"]:
            try:
                pp = json.loads(r["phylum_profile"])
                all_phyla.update(pp.keys())
            except (json.JSONDecodeError, TypeError):
                pass

    # Sort for determinism
    phylum_features = sorted(all_phyla)
    feature_names = phylum_features + _META_FEATURES
    logger.info("Feature matrix: %d phyla + %d env = %d features",
                len(phylum_features), len(_META_FEATURES), len(feature_names))

    X_rows: list[list[float]] = []
    y_vals: list[float] = []

    for r in rows:
        pp: dict[str, float] = {}
        if r["phylum_profile"]:
            try:
                pp = json.loads(r["phylum_profile"])
            except (json.JSONDecodeError, TypeError):
                pass

        row_vec = [pp.get(p, 0.0) for p in phylum_features]
        for meta in _META_FEATURES:
            val = r[meta]
            row_vec.append(float(val) if val is not None else _META_DEFAULTS[meta])

        X_rows.append(row_vec)
        y_vals.append(labels[r["sample_id"]])

    X = np.array(X_rows, dtype=float)
    y = np.array(y_vals, dtype=float)
    return X, y, feature_names


def _train_and_save(
    X: np.ndarray,
    y: np.ndarray,
    feature_names: list[str],
    out_dir: Path,
    apply_clr: bool = False,
) -> dict:
    """Train RF classifier + regressor and save to out_dir. Returns report dict."""
    try:
        import joblib
        from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
        from sklearn.model_selection import cross_val_score, StratifiedKFold, KFold
        from sklearn.pipeline import Pipeline
        from sklearn.preprocessing import StandardScaler
    except ImportError as exc:
        raise ImportError("scikit-learn and joblib required: pip install scikit-learn joblib") from exc

    from core.compute.functional_predictor import clr_transform

    out_dir.mkdir(parents=True, exist_ok=True)
    n, nf = X.shape
    logger.info("Training on %d samples × %d features (apply_clr=%s)", n, nf, apply_clr)

    X_proc = clr_transform(X) if apply_clr else X

    # ── Classifier (BNF-high = top 33% by published rate) ──────────────────
    threshold_33 = float(np.percentile(y, 67))  # top 33% = label 1
    y_clf = (y >= threshold_33).astype(int)
    pos_frac = y_clf.mean()
    logger.info("Classifier labels: %d positive (%.1f%%) above percentile-67 (%.4f)",
                y_clf.sum(), pos_frac * 100, threshold_33)

    clf_pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("clf", RandomForestClassifier(
            n_estimators=400,
            max_features="sqrt",
            min_samples_leaf=3,
            class_weight="balanced",
            oob_score=True,
            random_state=42,
            n_jobs=-1,
        )),
    ])
    cv_clf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_roc = cross_val_score(clf_pipeline, X_proc, y_clf, cv=cv_clf,
                              scoring="roc_auc", n_jobs=-1)
    clf_pipeline.fit(X_proc, y_clf)
    oob_acc = clf_pipeline.named_steps["clf"].oob_score_
    logger.info("Classifier CV ROC-AUC: %.4f ± %.4f; OOB acc: %.4f",
                cv_roc.mean(), cv_roc.std(), oob_acc)

    clf_payload = {
        "model": clf_pipeline,
        "model_type": "random_forest",
        "feature_names": feature_names,
        "apply_clr": apply_clr,
        "training_n": n,
        "pass_n": int(y_clf.sum()),
        "cv_roc_auc": float(cv_roc.mean()),
        "oob_accuracy": float(oob_acc),
        "feature_importances": dict(zip(
            feature_names,
            clf_pipeline.named_steps["clf"].feature_importances_.tolist(),
        )),
        "label_source": "published_bnf_rates",
        "label_threshold_percentile": 67,
        "label_threshold_value": threshold_33,
    }
    clf_path = out_dir / "bnf_surrogate_classifier_v2.joblib"
    joblib.dump(clf_payload, clf_path)
    logger.info("Saved classifier to %s", clf_path)

    # ── Regressor (continuous BNF rate) ────────────────────────────────────
    reg_pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("reg", RandomForestRegressor(
            n_estimators=400,
            max_features="sqrt",
            min_samples_leaf=3,
            oob_score=True,
            random_state=42,
            n_jobs=-1,
        )),
    ])
    cv_reg = KFold(n_splits=5, shuffle=True, random_state=42)
    cv_r2 = cross_val_score(reg_pipeline, X_proc, y, cv=cv_reg, scoring="r2", n_jobs=-1)
    reg_pipeline.fit(X_proc, y)
    oob_r2 = reg_pipeline.named_steps["reg"].oob_score_
    logger.info("Regressor CV R²: %.4f ± %.4f; OOB R²: %.4f",
                cv_r2.mean(), cv_r2.std(), oob_r2)

    # Spearman r on training data (in-sample — will be optimistic but useful sanity check)
    y_pred = reg_pipeline.predict(X_proc)
    from core.validate_pipeline import _spearman_r
    sp_r = _spearman_r(y_pred.tolist(), y.tolist())
    logger.info("In-sample Spearman r (regressor): %.4f", sp_r)

    reg_payload = {
        "model": reg_pipeline,
        "model_type": "random_forest",
        "feature_names": feature_names,
        "apply_clr": apply_clr,
        "training_n": n,
        "cv_r2": float(cv_r2.mean()),
        "oob_r2": float(oob_r2),
        "insample_spearman_r": float(sp_r),
        "feature_importances": dict(zip(
            feature_names,
            reg_pipeline.named_steps["reg"].feature_importances_.tolist(),
        )),
        "label_source": "published_bnf_rates",
    }
    reg_path = out_dir / "bnf_surrogate_regressor_v2.joblib"
    joblib.dump(reg_payload, reg_path)
    logger.info("Saved regressor to %s", reg_path)

    report = {
        "training_n": n,
        "n_features": nf,
        "classifier": {
            "cv_roc_auc": float(cv_roc.mean()),
            "cv_roc_auc_std": float(cv_roc.std()),
            "oob_accuracy": float(oob_acc),
            "label_threshold_percentile": 67,
            "label_source": "published_bnf_rates",
        },
        "regressor": {
            "cv_r2": float(cv_r2.mean()),
            "cv_r2_std": float(cv_r2.std()),
            "oob_r2": float(oob_r2),
            "insample_spearman_r": float(sp_r),
            "label_source": "published_bnf_rates",
        },
        "top_features": sorted(
            clf_payload["feature_importances"].items(),
            key=lambda x: x[1], reverse=True,
        )[:20],
    }
    report_path = out_dir / "retrain_report.json"
    report_path.write_text(json.dumps(report, indent=2))
    logger.info("Report written to %s", report_path)
    return report


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--db", required=True, help="Path to SQLite DB")
    parser.add_argument("--bnf-csv", required=True, help="Path to bnf_measurements.csv")
    parser.add_argument("--out-dir", default="apps/bnf/models/", help="Output directory")
    parser.add_argument("--no-clr", action="store_true",
                        help="Disable CLR transform (use if phylum profiles already normalised)")
    args = parser.parse_args()

    labels = _load_bnf_labels(Path(args.bnf_csv))
    X, y, feature_names = _build_feature_matrix(args.db, labels)
    report = _train_and_save(X, y, feature_names, Path(args.out_dir),
                             apply_clr=not args.no_clr)

    print(f"\n=== Retraining Complete ===")
    print(f"  Training samples : {report['training_n']:,}")
    print(f"  Features         : {report['n_features']}")
    print(f"  Classifier ROC-AUC (5-fold CV): {report['classifier']['cv_roc_auc']:.4f}")
    print(f"  Regressor R² (5-fold CV)      : {report['regressor']['cv_r2']:.4f}")
    print(f"  In-sample Spearman r          : {report['regressor']['insample_spearman_r']:.4f}")
    print(f"\nTop 10 predictive features:")
    for feat, imp in report["top_features"][:10]:
        print(f"  {feat:<35} {imp:.4f}")
    print(f"\nNext: run validate_pipeline.py with --model-path apps/bnf/models/bnf_surrogate_classifier_v2.joblib")
    print(f"Expected: Spearman r improvement from 0.35 toward 0.55–0.65")


if __name__ == "__main__":
    main()
